name: Build and Push Docker Image

on:
  # Trigger on push events to the main branch
  push:
    branches: [ master ]
  # Trigger on pull request events
  pull_request:
    types: [ opened, closed ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Workflow runs on Ubuntu virtual machines

    steps:
          #checkout code

      - name: Checkout
        uses: actions/checkout@v4
      #for multiple platforms
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    

          # login to own dockerhub 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
        # GitHub Repo->Settings->Secrets then add username and password
        # it should be the same with name here 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # - name: Set up test environment (replace with tests)
      #   # Add test commands here. For example:
      #   #  - run: pytest tests.py

      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev'}}
        name: Build && Push Docker image (edge - dev branch)
        working-directory: .
        run: | 
          docker build . --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:edge
          docker push ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:edge

      - if: ${{ github.event_name == 'pull_request' }}
        name: Build && Push Docker image (edge - pull request)
        working-directory: .
        run: |
          docker build . --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:${{ github.sha }}
 

      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        name: Build && Push Docker image (latest - main branch)
        working-directory: .
        run: | 
          docker build . --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:latest
    
